/**
 * Represents the structure of an API response.
 *
 * This interface defines the expected properties for a response object
 * generated by an API call. It includes information about the HTTP
 * status, encoding, response body, and headers.
 *
 * Properties:
 * - `statusCode`: The HTTP status code of the API response.
 * - `isBase64Encoded`: A flag indicating whether the body is base64-encoded.
 * - `body`: The content of the API response, typically in string format.
 * - `headers`: A key-value pair object representing the HTTP headers of the response.
 */
export interface IApiResponse {
    statusCode: number;
    isBase64Encoded: boolean;
    body: string;
    headers: Record<string, string>;
}
